/**
 * Migration: Relational Schema v2
 *
 * Introduces the full relational model covering all three fundamental
 * relationship types required by the project specification:
 *
 *   1:1  - projects - project_settings
 *          (projectId is BOTH primary key AND foreign key — the canonical
 *           SQL technique that guarantees exactly one settings row per project)
 *
 *   1:N  - projects - tags
 *          (each tag belongs to exactly one project; deleting the project
 *           removes all its tags via CASCADE)
 *
 *   N:M  - users - projects  via project_members
 *          (composite PK on [userId, projectId] prevents duplicate memberships)
 *
 *   N:M  - tasks - tags      via task_tags
 *          (composite PK on [taskId, tagId] prevents duplicate assignments)
 *
 * Additionally this migration changes the tasks.projectId foreign key
 * from ON DELETE SET NULL to ON DELETE CASCADE, so that deleting a project
 * removes all its tasks (coherent referential integrity).
 *
 * NOTE: projects.userId is NOT renamed here. The rename to createdByUserId
 * is done in Step 2 alongside the corresponding DAO/controller changes so
 * the running application is never left in an inconsistent state.
 *
 * @param { import("knex").Knex } knex
 */

exports.up = async function (knex) {

  // 1) project_settings  (1:1 with projects)
  //
  //    The primary key IS the foreign key. This is the standard relational
  //    pattern for 1:1: a row can only exist if the referenced project exists, and there can be at most one row per project (PK uniqueness).

  await knex.schema.createTable('project_settings', (table) => {
    table.uuid('projectId').primary(); // PK + FK — enforces the 1:1 guarantee
    table
      .foreign('projectId')
      .references('id')
      .inTable('projects')
      .onDelete('CASCADE'); // settings disappear with their project
    table.text('description').nullable();
    table.string('color', 7).notNullable().defaultTo('#4c90f0'); // hex display color for the chip
    table.boolean('isPublic').notNullable().defaultTo(true); // controls global visibility
    table.timestamp('createdAt').defaultTo(knex.fn.now());
  });

  // 2) project_members  (N:M — users - projects)
  //
  //    A user can belong to many projects; a project can have many users.
  //    The composite primary key [userId, projectId] makes duplicates structurally impossible at the database level.
  //    role is a string enum:  'OWNER' | 'MEMBER'

  await knex.schema.createTable('project_members', (table) => {
    table
      .uuid('userId')
      .notNullable()
      .references('id')
      .inTable('users')
      .onDelete('CASCADE'); // leaving user is removed from all projects
    table
      .uuid('projectId')
      .notNullable()
      .references('id')
      .inTable('projects')
      .onDelete('CASCADE'); // deleted project removes all memberships
    table.string('role', 20).notNullable().defaultTo('MEMBER'); // 'OWNER' | 'MEMBER'
    table.timestamp('joinedAt').defaultTo(knex.fn.now());
    table.primary(['userId', 'projectId']); // composite PK — no duplicate memberships
  });

  // 3) tags  (1:N — projects - tags)
  //
  //    Each tag belongs to exactly one project. Tags are scoped to their
  //    project (like Odoo's project tags) so "Bug" in Project A is distinct from "Bug" in Project B — they can have different colors.

  await knex.schema.createTable('tags', (table) => {
    table.uuid('id').primary();
    table.string('name', 50).notNullable();
    table.string('color', 7).notNullable().defaultTo('#8a9ba8'); // muted grey default
    table
      .uuid('projectId')
      .notNullable()
      .references('id')
      .inTable('projects')
      .onDelete('CASCADE'); // tags deleted with their project
    table.timestamp('createdAt').defaultTo(knex.fn.now());
  });

  // 4) task_tags  (N:M — tasks - tags)
  //
  //    A task can have multiple tags; a tag can be applied to multiple tasks.
  //    Composite PK prevents assigning the same tag to the same task twice.
  //    Both FKs use CASCADE so the pivot row is cleaned up automatically when either the task or the tag is deleted.

  await knex.schema.createTable('task_tags', (table) => {
    table
      .uuid('taskId')
      .notNullable()
      .references('id')
      .inTable('tasks')
      .onDelete('CASCADE');
    table
      .uuid('tagId')
      .notNullable()
      .references('id')
      .inTable('tags')
      .onDelete('CASCADE');
    table.primary(['taskId', 'tagId']); // composite PK — no duplicate assignments
  });

  // 5) Change tasks.projectId FK: SET NULL - CASCADE DELETE
  //
  //    Tasks without a project make no sense if the project was their context.
  //    Coherent referential integrity requires that deleting a project removes all its tasks.
  //    We cannot use knex's .alter() for FK changes in Knex 3.x + PG, so we use raw SQL. The existing constraint name is auto-generated by Knex and
  //    may vary; we use a PL/pgSQL DO block to look it up dynamically from the information schema instead of hardcoding it.

  await knex.raw(`
    DO $$
    DECLARE
      v_constraint_name text;
    BEGIN
      -- Find the existing FK constraint on tasks."projectId" by looking at
      -- the information schema (reliable across Knex versions and PG versions)
      SELECT tc.constraint_name
        INTO v_constraint_name
        FROM information_schema.table_constraints AS tc
        JOIN information_schema.key_column_usage  AS kcu
          ON tc.constraint_name = kcu.constraint_name
         AND tc.table_schema    = kcu.table_schema
       WHERE tc.table_name      = 'tasks'
         AND tc.constraint_type = 'FOREIGN KEY'
         AND kcu.column_name    = 'projectId'
       LIMIT 1;

      IF v_constraint_name IS NOT NULL THEN
        EXECUTE 'ALTER TABLE tasks DROP CONSTRAINT ' || quote_ident(v_constraint_name);
      END IF;
    END $$;
  `);

  // Re-add the FK with CASCADE DELETE
  await knex.raw(`
    ALTER TABLE tasks
      ADD CONSTRAINT tasks_projectid_foreign
      FOREIGN KEY ("projectId")
      REFERENCES projects(id)
      ON DELETE CASCADE
  `);

  // 6) Back-fill existing data
  //
  //    Projects that existed before this migration need:
  //      a) A row in project_settings (with sensible defaults)
  //      b) A row in project_members marking the creator as OWNER
  //
  //    This keeps the DB consistent for existing users without touching the application code (which is updated separately in Step 2).

  const existingProjects = await knex('projects').select('id', 'userId');

  if (existingProjects.length > 0) {
    await knex('project_settings').insert(
      existingProjects.map((project) => ({
        projectId: project.id,
        description: null,
        color: '#4c90f0',
        isPublic: true,
      }))
    );

    await knex('project_members').insert(
      existingProjects.map((project) => ({
        userId: project.userId,
        projectId: project.id,
        role: 'OWNER',
      }))
    );
  }
};

exports.down = async function (knex) {

    // Reverse in dependency order (children before parents)

  await knex.schema.dropTableIfExists('task_tags');
  await knex.schema.dropTableIfExists('tags');
  await knex.schema.dropTableIfExists('project_members');
  await knex.schema.dropTableIfExists('project_settings');

  // Restore tasks.projectId FK to SET NULL (original behaviour)
  await knex.raw(`
    DO $$
    DECLARE
      v_constraint_name text;
    BEGIN
      SELECT tc.constraint_name
        INTO v_constraint_name
        FROM information_schema.table_constraints AS tc
        JOIN information_schema.key_column_usage  AS kcu
          ON tc.constraint_name = kcu.constraint_name
         AND tc.table_schema    = kcu.table_schema
       WHERE tc.table_name      = 'tasks'
         AND tc.constraint_type = 'FOREIGN KEY'
         AND kcu.column_name    = 'projectId'
       LIMIT 1;

      IF v_constraint_name IS NOT NULL THEN
        EXECUTE 'ALTER TABLE tasks DROP CONSTRAINT ' || quote_ident(v_constraint_name);
      END IF;
    END $$;
  `);

  await knex.raw(`
    ALTER TABLE tasks
      ADD CONSTRAINT tasks_projectid_foreign
      FOREIGN KEY ("projectId")
      REFERENCES projects(id)
      ON DELETE SET NULL
  `);
};
